--CREATE TABLE IF NOT EXISTS example (
--  id BIGINT NOT NULL  PRIMARY KEY,
--  first_name VARCHAR(250),
--  last_name VARCHAR(250),
--  mobile_number INTEGER NOT NULL,
--  PRIMARY KEY (id) engine=MyISAM
--);
-- 
--INSERT INTO example (first_name, last_name, mobile_number) VALUES
--  ('Aliko', 'Dangote', 1000),
--  ('Bill', 'Gates', 350),
--  ('Folrunsho', 'Alakija', 3500);